In [1]:
import pandas as pd
import numpy as np
import re
import requests
from io import StringIO
import os

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [8]:
import requests
import pandas as pd

url = "http://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=json&per_page=20000"
response = requests.get(url)

if response.status_code == 200:
    data = response.json()[1]  # Get the data from the second element of the response
    df = pd.json_normalize(data)  # Convert the JSON data into a pandas DataFrame
    print(df.head())
else:
    print("Request failed with status code:", response.status_code)

  countryiso3code  date        value unit obs_status  decimal indicator.id  \
0             AFE  2022          NaN                        0  SP.POP.TOTL
1             AFE  2021  702976832.0                        0  SP.POP.TOTL
2             AFE  2020  685112705.0                        0  SP.POP.TOTL
3             AFE  2019  667242712.0                        0  SP.POP.TOTL
4             AFE  2018  649756874.0                        0  SP.POP.TOTL

     indicator.value country.id                country.value
0  Population, total         ZH  Africa Eastern and Southern
1  Population, total         ZH  Africa Eastern and Southern
2  Population, total         ZH  Africa Eastern and Southern
3  Population, total         ZH  Africa Eastern and Southern
4  Population, total         ZH  Africa Eastern and Southern

In [10]:
df

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2022,NaN,,,0,SP.POP.TOTL,"Population, total",ZH,Africa Eastern and Southern
1,AFE,2021,702976832.0,,,0,SP.POP.TOTL,"Population, total",ZH,Africa Eastern and Southern
2,AFE,2020,685112705.0,,,0,SP.POP.TOTL,"Population, total",ZH,Africa Eastern and Southern
3,AFE,2019,667242712.0,,,0,SP.POP.TOTL,"Population, total",ZH,Africa Eastern and Southern
4,AFE,2018,649756874.0,,,0,SP.POP.TOTL,"Population, total",ZH,Africa Eastern and Southern
...,...,...,...,...,...,...,...,...,...,...
16753,ZWE,1964,4310332.0,,,0,SP.POP.TOTL,"Population, total",ZW,Zimbabwe
16754,ZWE,1963,4177931.0,,,0,SP.POP.TOTL,"Population, total",ZW,Zimbabwe
16755,ZWE,1962,4049778.0,,,0,SP.POP.TOTL,"Population, total",ZW,Zimbabwe
16756,ZWE,1961,3925952.0,,,0,SP.POP.TOTL,"Population, total",ZW,Zimbabwe
16757,ZWE,1960,3806310.0,,,0,SP.POP.TOTL,"Population, total",ZW,Zimbabwe

In [14]:
df = df.rename(columns={'countryiso3code': 'country_code', 'indicator.id': 'indicator_id', 'indicator.value': 'indicator_value', 'date': 'year', 'country.value': 'Country', 'value':'population'})

In [15]:
df.to_csv('../data/population.csv')